# Generated by Django 4.0.4 on 2023-03-05 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('phone_num1', models.IntegerField(max_length=15)),
                ('phone_num2', models.IntegerField(blank=True, max_length=15, null=True)),
                ('company', models.CharField(max_length=30)),
                ('join_date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
