# Generated by Django 4.0.4 on 2023-03-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_num1',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_num2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
