# Generated by Django 4.0.4 on 2023-03-05 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='To_Do',
            new_name='ToDo',
        ),
    ]
